テストを作成
SuzukaHori/fjord-books_app-2023 pull request #9
Opened 2023-09-19 06:16 UTC by SuzukaHori

テストを追加しました。
レビューをお願いします🙇‍♀️

2023-09-24 16:29 UTC, u1tnk requested changes
だいたい良さそうです！
ちょっと気になったところをいくつかコメントしました。

2023-09-24 16:29 UTC, u1tnk commented on test/test_helper.rb
> +    fill_in 'Eメール', with: 'suzuka@example.com'
ここは userをすぐ前で作っているので `user.email` で指定すれば良いですね。

2023-09-24 16:29 UTC, u1tnk commented on test/test_helper.rb
> +    sleep 1
実務でも sleep に頼る事もありますが最終手段ですね。
この場合だと 何かをassertすればその対象を待ってくれるはずなので、ログインできたことをassertしておきましょう。

2023-09-24 16:29 UTC, u1tnk commented on test/system/comments_test.rb
> +    visit report_url(@report)
削除をテストしたいのであれば事前にデータをFactoryBotで作った方がシンプルになりそう。
作成のテストと一緒にしても良いです。

2023-09-25 07:43 UTC, SuzukaHori commented on test/test_helper.rb
> +    fill_in 'Eメール', with: 'suzuka@example.com'
その通りでした💦

直接書いていた部分を`user.email`の書き方に修正しました。パスワードの方も同様に修正しました。https://github.com/SuzukaHori/fjord-books_app-2023/pull/9/commits/e193349deb1f7de2e3a6284e49b7aedb32947d2b

2023-09-25 07:45 UTC, SuzukaHori commented on test/test_helper.rb
> +    sleep 1
`sleep`は最終手段なんですね。
なるべく使用しないようにします🤔

`assert`を使う書き方に変更しました。（テストの実行速度が早くなりました！）https://github.com/SuzukaHori/fjord-books_app-2023/pull/9/commits/e193349deb1f7de2e3a6284e49b7aedb32947d2b

2023-09-25 07:54 UTC, SuzukaHori commented on test/system/comments_test.rb
> +    visit report_url(@report)
確かにここでわざわざコメント作成するのは冗長ですね💦

`test/factories/comments.rb`で事前にコメントを作り、それを削除する方法に変更しました。https://github.com/SuzukaHori/fjord-books_app-2023/pull/9/commits/d64d58c55d3e6928a1365c2a3bfd60d0f723571e

2023-09-25 15:52 UTC, u1tnk commented on test/test_helper.rb
> +    fill_in 'Eメール', with: 'suzuka@example.com'
補足すると、パスワードは実運用ではDBに保存せず、パスワードから作った sha256 などの hash処理の結果を保存します。
(プラクティスでは問題無いです)

2023-09-25 15:52 UTC, u1tnk approved these changes

2023-09-26 01:04 UTC, SuzukaHori commented on test/test_helper.rb
> +    fill_in 'Eメール', with: 'suzuka@example.com'
実務ではテストデータを書くときも、パスワードを直接書かない＆取得できないようにするのですね。次回テストを書く時には、そのようにしたいと思います❣️

2023-09-26 23:12 UTC, u1tnk commented on test/test_helper.rb
> +    fill_in 'Eメール', with: 'suzuka@example.com'
テストデータに適当なパスワードは書きますよ。testとかhogeとかランダム文字列とか。（本当に使えるものは書いてはいけませんが）
データベースには保存しないということです！

2023-09-27 00:47 UTC, SuzukaHori commented on test/test_helper.rb
> +    fill_in 'Eメール', with: 'suzuka@example.com'
テストデータの話だと誤解していました💦
実際の環境では、パスワードをDBには直接保存せず、ハッシュ値をDBに保存すると理解しました。

ありがとうございます🙇‍♀️

2023-10-03 05:09 UTC, merged